### ISSUE TITLE
Camera intermittantly issues 192.168.50.x addresses to devices on my home network.

### ISSUE THREAD

**Issue by QQOak** [interactionresearchstudio/NaturewatchCameraServer#83]
My camera is connected via WiFi to my home network and intermittantly issues a 192.168.50.x/24 address to machines on the network even though my router is issuing 192.168.0.x/24 addresses

** To reproduce **
Connect the naturewatch camera to a wifi network.
Issue is intermittant, a lot of disconnecting and reconnecting wifi on a phone or tablet or unplugging and plugging back in of ethernet of a desktop can be needed.  I cannot reproduce on demand.

Once a device has got a lease for a 192.168.50.x address from the camera, only way I've found to fix is to switch the camera off, and reboot the affected device to get a new lease from my router.

** Expected behavior **
I would expect the DHCP server within the camera to only be operational when it's acting as an access point.

** Experienced on **
Windows 10 20H2, when connecting to WiFi or Ethernet
IPad 2
Samsang Galaxy A52

Camera is a stock Pi Zero W with rpi NOIR.

This can be a pain to reproduce as I can't get client devices to prefer the camera DHCP server over Virgin Media's router on purpose.

**Comment by mikevanis** [comment]
Hi there, thanks for the report. The networking setup is all handled by the auto-hotspot module within [CustomPiOS](https://github.com/guysoft/CustomPiOS). Unfortunately in order to stop this issue from happening, we would need to change the underlying mechanism for switching between WiFi client and WiFi hotspot within the CustomPiOS module. 

I suggest that you open an issue over on their repository. If it gets fixed on their end, our cloud builder will pick up the change and integrate it within our software too.
