### ISSUE TITLE
Linux development & video flow

### ISSUE THREAD

**Issue by tmaziere** [interactionresearchstudio/NaturewatchCameraServer#85]
Hi,

I'm fond of this project and as a developer i would like to contribute in the future (and my colleagues, too). 

I managed to run the repo through Docker on a Debian-based OS (Mint), but i was unable to use the video flow as is.
[You test if *picamera* is available](https://github.com/interactionresearchstudio/NaturewatchCameraServer/blob/c168da465a391ab4029ab0b64c02db4ee32ab6f8/naturewatch_camera_server/CameraController.py#L59) and implement a webcam alternative, so should we be able to develop on an amd linux OS (or more generally speaking, on a laptop)?

--
Thomas

**Comment by mikevanis** [comment]
Hi, thanks for your interest in the project! 

The focus for the project is a **small, affordable wildlife camera based on the Raspberry Pi**. We have some basic functionality on non-pi environments, specifically so we can develop the web app user interface for the camera. It's very basic. It can take photos so that the gallery is filled up with content to test UI. Video is currently not working without picamera, since it relies on the circular buffering of the picamera library. You can extend the CameraController class to handle more situations you need as you develop. 

FYI we will probably drop Docker support quite soon. If you can, set up a clean environment with OpenCV on your preferred system. You can use our image builder's [shell script](https://github.com/interactionresearchstudio/NaturewatchCameraServer/blob/c168da465a391ab4029ab0b64c02db4ee32ab6f8/os/modules/naturewatchcamera/start_chroot_script) as a starting point, which is for the Raspberry Pi. We're dropping Docker because we now have a Raspberry Pi image builder on GitHub actions that installs everything, sets up networking, and outputs an iso image to burn on an SD card. Therefore, Docker isn't so useful anymore; it's a bit overkill and is a massive memory hoarder on the Pi Zero. 

Let me know if you need any more info! Closing this as the question is answered for now.
